version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
  environment:
    - NODE_ENV=production
    - SUPABASE_URL=${SUPABASE_URL}
    - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
    - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    - OPENAI_API_KEY=${OPENAI_API_KEY}
  volumes:
    - .:/app
    - /app/node_modules